trigger:
- dev

pr:
- dev

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformDeployment
  displayName: 'Terraform Deployment'
  steps:
  - checkout: self
    submodules: true

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '3.x'
      performMultiLevelLookup: true

  - script: |
      cd azure-1
      terraform init
    displayName: 'Terraform Init'

  - script: |
      cd azure-1
      terraform validate
    displayName: 'Terraform Validate'

  - script: |
      cd azure-1
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - powershell: |
      $result = Read-Host "Do you want to apply the Terraform changes? Type 'Approve' to apply, or 'Reject' to cancel."

      if ($result -ne "Approve") {
          Write-Output "Pipeline execution canceled."
          exit 1
      }
    displayName: 'Prompt for Approval'

  - script: |
      cd azure-1
      terraform apply -auto-approve tfplan
    displayName: 'Apply Terraform Changes'
    condition: succeededOrFailed()  # Continue regardless of manual approval result
