trigger:
- dev

pr:
- dev

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformDeployment
  displayName: 'Terraform Deployment'
  steps:
  - checkout: self
    submodules: true

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '3.x'
      performMultiLevelLookup: true

  - script: |
      ls -la
      cd $(Build.SourcesDirectory)/azure-1
      terraform init
    displayName: 'Terraform Init'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform validate
    displayName: 'Terraform Validate'

  - script: |
      az login 

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform plan -out=tfplan -input=false
    displayName: 'Terraform Plan'

  - script: |
      if [ "$APPROVE_TF_CHANGES" != "yes" ]; then
          echo "Pipeline execution canceled due to lack of approval."
          exit 1
      fi
    displayName: 'Prompt for Approval'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform apply -auto-approve tfplan
    displayName: 'Apply Terraform Changes'
    condition: succeededOrFailed()
