trigger:
- dev

pr:
- dev

variables:
  requireApproval: true
  TF_APPROVE: 'no'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformDeployment
  displayName: 'Terraform Deployment'
  steps:
  - checkout: self
    submodules: true

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '3.x'
      performMultiLevelLookup: true

  - script: |
      ls -la
      cd $(Build.SourcesDirectory)/azure-1
      terraform init
    displayName: 'Terraform Init'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform validate
    displayName: 'Terraform Validate'

  - script: |
      az login 

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform plan -out=tfplan -input=false
    displayName: 'Terraform Plan'

  - script: |
      echo 'no' > tf_approval.txt
      if [ "$(cat tf_approval.txt)" == "yes" ]; then
        cd $(Build.SourcesDirectory)/azure-1
        terraform apply -auto-approve tfplan
      else
        echo "Pipeline execution canceled."
      fi
    displayName: 'Apply Terraform Changes'
