trigger:
- dev

pr:
- dev

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformDeployment
  displayName: 'Terraform Deployment'
  steps:
  - checkout: self
    submodules: true

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '3.x'
      performMultiLevelLookup: true

  - script: |
      ls -la   # List files in the current directory for debugging
      pwd      # Print the current working directory for debugging
      cd $(Build.SourcesDirectory)/azure-1
      pwd      # Print the current working directory again for debugging
      terraform init
    displayName: 'Terraform Init'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      ls -la   # List files in the current directory for debugging
      terraform validate
    displayName: 'Terraform Validate'

  - script: |
      az login 

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform plan -out=tfplan -input=false
    displayName: 'Terraform Plan'

  - script: |
      echo "Do you want to apply the Terraform changes? Set TF_APPROVE='yes' to apply, or 'no' to cancel."
      echo "##vso[task.setvariable variable=TF_APPROVE;isOutput=true]$(read -p 'Type your answer (yes/no): ' TF_APPROVE && echo $TF_APPROVE)"
    displayName: 'Prompt for Approval'

  - script: |
      if [ "${TF_APPROVE}" != "yes" ]; then
          echo "Pipeline execution canceled."
          exit 1
      fi
    displayName: 'Check Approval and Apply Terraform'
    condition: succeededOrFailed()   # Continue regardless of manual approval result
