trigger:
- dev

pr:
- dev

variables:
  requireApproval: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformDeployment
  displayName: 'Terraform Deployment'
  steps:
  - checkout: self
    submodules: true

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '3.x'
      performMultiLevelLookup: true

  - script: |
      ls -la
      cd $(Build.SourcesDirectory)/azure-1
      terraform init
    displayName: 'Terraform Init'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform validate
    displayName: 'Terraform Validate'

  - script: |
      az login 

  - script: |
      read -p "Do you want to apply the Terraform changes? Type 'yes' to apply, or 'no' to cancel: " result

      if [ "$result" != "yes" ]; then
          echo "Pipeline execution canceled."
          exit 1
      else
          echo "##vso[task.setvariable variable=requireApproval]false"
      fi
    displayName: 'Prompt for Approval'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform plan -out=tfplan -input=false
    displayName: 'Terraform Plan'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      echo "Applying Terraform Changes..."
      terraform apply -auto-approve tfplan
    displayName: 'Apply Terraform Changes'
    condition: eq(variables['requireApproval'], false)
