trigger:
- dev

pr:
- dev

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformDeployment
  displayName: 'Terraform Deployment'
  steps:
    - checkout: self
      submodules: true

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        version: '3.x'
        performMultiLevelLookup: true

    - script: |
        ls -la
        pwd
        cd $(Build.SourcesDirectory)/azure-1
        pwd
        terraform init
      displayName: 'Terraform Init'

    - script: |
        cd $(Build.SourcesDirectory)/azure-1
        ls -la
        terraform validate
      displayName: 'Terraform Validate'

    - script: |
        az login 
      displayName: 'Azure Login'

    - script: |
        cd $(Build.SourcesDirectory)/azure-1
        terraform plan -out=tfplan -input=false
      displayName: 'Terraform Plan'

    - task: ManualIntervention@8
  displayName: 'Prompt for Approval'
  inputs:
    instructions: 'Review Terraform changes and approve if necessary'
    notifyUsers: 'me@example.com'
    timeoutInMinutes: 1440

    - script: |
        cd $(Build.SourcesDirectory)/azure-1
        terraform apply -auto-approve tfplan
      displayName: 'Apply Terraform Changes'

