trigger:
- dev

pr:
- dev

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: terraform_approval
  displayName: "Terraform Approval"
  steps:
    - script: 
        echo "Terraform Approval Job"
      displayName: 'Terraform Approval'
      condition: succeededOrFailed()

- job: manual_approval
  displayName: "Manual Approval"
  dependsOn: terraform_approval
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: 
        echo "Manual Approval Job"
      displayName: 'Manual Approval'
      condition: succeededOrFailed()

    - script: |
        ls -la
        pwd
        cd $(Build.SourcesDirectory)/azure-1
        pwd
        terraform init
      displayName: 'Terraform Init'

    - script: |
        cd $(Build.SourcesDirectory)/azure-1
        terraform validate
      displayName: 'Terraform Validate'

    - script: |
        az login 
    - script: |
        cd $(Build.SourcesDirectory)/azure-1
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'

- job: manual_intervention
  displayName: 'Manual Approval Intervention'
  dependsOn: manual_approval
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: ManualIntervention@1
      inputs:
        instructions: 'Please review and manually approve the Terraform changes.'
        notifyUsers: 'all'
