trigger:
- dev

pr:
- dev

variables:
  requireApproval: false

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformDeployment
  displayName: 'Terraform Deployment'
  steps:
  - checkout: self
    submodules: true

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '3.x'
      performMultiLevelLookup: true

  - script: |
      ls -la
      cd $(Build.SourcesDirectory)/azure-1
      terraform init
    displayName: 'Terraform Init'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform validate
    displayName: 'Terraform Validate'

  - script: |
      az login 

  - script: |
      echo "requireApproval: $(requireApproval)"
      if [ "$(requireApproval)" == "true" ]; then
          echo "Pipeline execution requires approval."
          exit 1
      fi
    displayName: 'Check for Approval'

  - task: ManualValidation@2
    displayName: 'Manual Approval'
    inputs:
      instructions: 'Review the Terraform changes and approve or reject.'
      onTimeout: 'reject'
      timeoutInMinutes: 1440 # 24 hours

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform plan -out=tfplan -input=false
    displayName: 'Terraform Plan'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      echo "Applying Terraform Changes..."
      terraform apply -auto-approve tfplan
    displayName: 'Apply Terraform Changes'
    condition: eq(variables['requireApproval'], false)
