trigger:
- dev

pr:
- dev

variables:
  requireApproval: true
  TF_APPROVE: 'no'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformDeployment
  displayName: 'Terraform Deployment'
  steps:
  - checkout: self
    submodules: true

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '3.x'
      performMultiLevelLookup: true

  - script: |
      ls -la
      cd $(Build.SourcesDirectory)/azure-1
      terraform init
    displayName: 'Terraform Init'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform validate
    displayName: 'Terraform Validate'

  - script: |
      az login 

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform plan -out=tfplan -input=false
    displayName: 'Terraform Plan'

  - script: |
      echo "##vso[task.setvariable variable=TF_APPROVE]$(read -p 'Do you want to apply the Terraform changes? Type ''yes'' to apply, or ''no'' to cancel: '; echo $REPLY)"
    displayName: 'Prompt for Approval'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform apply -auto-approve tfplan
    displayName: 'Apply Terraform Changes'
    condition: eq(variables['TF_APPROVE'], 'yes')

