

trigger:
- dev

pr:
- dev

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformDeployment
  displayName: 'Terraform Deployment'
  steps:
  - checkout: self
    submodules: true

- job: manual_approval
  displayName: "Manual Approval"
  dependsOn: terraform_approval
  pool: server
  steps:
  - task: ManualValidation@0
    timeoutInMinutes: 5
    inputs:
      instructions: "Hi, please validate"

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '3.x'
      performMultiLevelLookup: true

  - script: |
      ls -la   
      pwd      
      cd $(Build.SourcesDirectory)/azure-1
      pwd     
      terraform init
    displayName: 'Terraform Init'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      ls -la   # List files in the current directory for debugging
      terraform validate
    displayName: 'Terraform Validate'

  - script: |
      az login 
  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      ls -la   # List files in the current directory for debugging
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: |
      read -p "Do you want to apply the Terraform changes? Type 'y' to apply, or 'n' to cancel: " result
      if [ "$result" != "y" ]; then
          echo "Pipeline execution canceled."
          exit 1
      fi
    displayName: 'Prompt for Approval'

  - script: |
      cd $(Build.SourcesDirectory)/azure-1
      terraform apply -auto-approve tfplan
    displayName: 'Apply Terraform Changes'
    condition: succeededOrFailed()