trigger:
- dev

pr:
- dev

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformDeployment
  displayName: 'Terraform Deployment'
  steps:
    - checkout: self
      submodules: true

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        version: '3.x'
        performMultiLevelLookup: true

    - script: |
        ls -la
        pwd
        cd $(Build.SourcesDirectory)/azure-1
        pwd
        terraform init
      displayName: 'Terraform Init'

    - script: |
        cd $(Build.SourcesDirectory)/azure-1
        ls -la
        terraform validate
      displayName: 'Terraform Validate'

    - script: |
        az login 
      displayName: 'Azure Login'

    - script: |
        cd $(Build.SourcesDirectory)/azure-1
        terraform plan -out=tfplan -input=false
      displayName: 'Terraform Plan'

    - script: |
        echo "##vso[task.setvariable variable=TF_APPROVE;isOutput=true;]$(System.DefaultWorkingDirectory)/tf_approve.txt"
        echo "Do you want to apply the Terraform changes? Type 'yes' to apply, or 'no' to cancel."
        echo "yes" > $(System.DefaultWorkingDirectory)/tf_approve.txt # Default value for testing
        cat $(System.DefaultWorkingDirectory)/tf_approve.txt
      displayName: 'Prompt for Approval'

    - script: |
        TF_APPROVE=$(cat $(System.DefaultWorkingDirectory)/tf_approve.txt)
        if [ "$TF_APPROVE" == "yes" ]; then
            echo "Applying Terraform Changes..."
            terraform apply -auto-approve tfplan
        else
            echo "Pipeline execution canceled."
            exit 1
        fi
      displayName: 'Apply Terraform Changes'
