trigger:
- dev

pr:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_APPROVE: 'no'  # Default value, change as needed

jobs:
- job: TerraformDeployment
  displayName: 'Terraform Deployment'
  steps:
    - checkout: self
      submodules: true

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        version: '3.x'
        performMultiLevelLookup: true

    - script: |
        ls -la
        pwd
        cd $(Build.SourcesDirectory)/azure-1
        pwd
        terraform init
      displayName: 'Terraform Init'

    - script: |
        cd $(Build.SourcesDirectory)/azure-1
        ls -la
        terraform validate
      displayName: 'Terraform Validate'

    - script: |
        az login 
      displayName: 'Azure Login'

    - script: |
        cd $(Build.SourcesDirectory)/azure-1
        terraform plan -out=tfplan -input=false
      displayName: 'Terraform Plan'

    - script: |
        echo "Do you want to apply the Terraform changes?"
        echo "TF_APPROVE=$(TF_APPROVE)"
        echo "##vso[task.setvariable variable=TF_APPROVE;isOutput=true]$(TF_APPROVE)"
      displayName: 'Prompt for Approval'

    - script: |
        if [ "$(TF_APPROVE)" == "yes" ]; then
            echo "Proceeding with applying Terraform changes..."
            terraform apply -auto-approve tfplan
        else
            echo "Pipeline execution canceled. No changes will be applied."
        fi
      displayName: 'Apply Terraform Changes'
